---
- hosts: localhost
  connection: local

  vars_prompt:
    - name: "ssh_passphrase"
      prompt: "Enter the passphrase for the SSH key"

  pre_tasks:
    - name: Update repositories
      become: yes
      apt: update_cache=yes
      changed_when: False
      
  tasks:
    - include: wsl2/packages.yml
    - include: wsl2/keys.yml
