---
- hosts: localhost
  connection: local

  vars_prompt:
    - name: "ssh_passphrase"
      prompt: "Enter the passphrase for the SSH key"

  pre_tasks:
    - name: Update repositories
      become: yes
      apt: update_cache=yes force_apt_get=yes
    - name: Update packages
      become: yes
      apt: upgrade=dist force_apt_get=yes
      
  tasks:
    - include: wsl2/packages.yml
    - include: wsl2/keys.yml
    - include: ubuntu/docker.yml
    - include: generic/sdkman.yml
